name: CI/CD Pipeline
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, edited]

jobs: 
  code-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v6
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Installing dependencies
      run: npm install
    - name: Run linting
      run: npm run lint
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: code
        path: ./github.workspace/*
